kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts: 
  - hostPath: /home/dane/Documents/Coding/k8s-web-service/reviews-service/dumps
    containerPath: /data
- role: worker
